#!/usr/bin/env bash
# this script audit DNS record for specified subdomain to a domain

function audit_subdomain {
    local domain="$1"
    local subdomain="$2"
    if [ -z "$subdomain" ]; then
	subdomain=("www" "lb-01" "web-01" "web-02")
    else
	subdomain=("$subdomain")
    fi

    for sub in "${subdomains[0]}"; do
	record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
	destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
	echo "The subdomain $sub is a $record_type record and points t $destination"
    done

    }
    audit_subdomain "$1" "$2"
