#!/usr/bin/env bash
# configure a ufw firewall to incoming traffic

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw defaault allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
